# Generated by Django 4.2 on 2023-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='port')),
                ('name', models.CharField(max_length=250)),
                ('descr', models.TextField()),
            ],
        ),
    ]
