# Generated by Django 4.2 on 2023-04-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='names',
        ),
    ]
